const Q=window.AMOC_QUESTIONS; const LS='amoc-diagnostic-v1';
const home=document.querySelector('#home'),quiz=document.querySelector('#quiz'),result=document.querySelector('#result');
let S=JSON.parse(localStorage.getItem(LS)||'null')||{order:[],i:0,answers:{},mode:'full'};
const esc=s=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const shuffle=a=>{a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};
function save(){localStorage.setItem(LS,JSON.stringify(S))}
function currentSet(){return S.order.map(id=>Q.find(q=>q.id===id)).filter(Boolean)}
function homeView(){home.classList.remove('hidden');quiz.classList.add('hidden');result.classList.add('hidden');const done=Object.keys(S.answers).length;home.innerHTML=`<div class=hero><span class=topic>AMOC SS26</span><h2>Gesamtdiagnose</h2><p class=muted>Die Fragen decken Grundlagen, Symmetrie, Bindung, Komplexchemie, Ligandenfeld, Reaktivität, Spektroskopie sowie die gesamte Stoffchemie ab. Themen und Antwortreihenfolge werden gemischt.</p></div><div class=grid><div class=stat><strong>${Q.length}</strong>Fragen im Pool</div><div class=stat><strong>${done}</strong>bereits beantwortet</div><div class=stat><strong>${Q.filter(x=>x.part==='Teil 1').length}</strong>Teil 1</div><div class=stat><strong>${Q.filter(x=>x.part==='Teil 2').length}</strong>Teil 2</div></div><p class="small muted">Hinweise sind erlaubt, werden aber separat gezählt. Ein richtiges Ergebnis nach Hinweis ist diagnostisch weniger aussagekräftig als ein unassistiertes richtiges Ergebnis.</p><div class=actions><button class=primary id=start>${done&&S.order.length?'Fortsetzen':'Gesamtdiagnose starten'}</button>${done?'<button class=secondary id=showres>Zwischenauswertung</button>':''}</div>`;document.querySelector('#start').onclick=startFull;if(done)document.querySelector('#showres').onclick=results}
function startFull(){if(!S.order.length||S.i>=S.order.length){S={order:shuffle(Q.map(x=>x.id)),i:0,answers:{},mode:'full'};save()} renderQ()}
function renderQ(){home.classList.add('hidden');result.classList.add('hidden');quiz.classList.remove('hidden');const arr=currentSet();if(S.i>=arr.length)return results();const q=arr[S.i],prev=S.answers[q.id],pct=Math.round(S.i/arr.length*100);quiz.innerHTML=`<div class=meta><span>Frage ${S.i+1} / ${arr.length}</span><span>${prev?'beantwortet':''}</span></div><div class=progress><span style="width:${pct}%"></span></div><div class=question>${esc(q.q)}</div><div class=answers>${q.opts.map((o,k)=>`<button class="answer ${prev?(k===q.a?'correct':(k===prev.sel?'wrong':'')):''}" data-k=${k} ${prev?'disabled':''}>${String.fromCharCode(65+k)}. ${esc(o.t)}${prev?`<span class=explain>${esc(o.e)}</span>`:''}</button>`).join('')}</div><div id=hintbox>${prev?.hint?`<div class=hint><strong>Hinweis:</strong> ${esc(q.hint)}</div>`:''}</div><div class=actions>${!prev?'<button class=secondary id=hint>Hinweis</button>':''}${prev?'<button class=primary id=next>Weiter</button>':''}<button class=ghost id=quit>Zur Übersicht</button></div>${prev?`<p class="small muted">Thema nach Beantwortung: <span class=topic>${esc(q.part)} · ${esc(q.topic)}</span></p>`:''}`;if(!prev){document.querySelectorAll('.answer').forEach(b=>b.onclick=()=>answer(q,+b.dataset.k));document.querySelector('#hint').onclick=()=>{q._hintUsed=true;document.querySelector('#hintbox').innerHTML=`<div class=hint><strong>Hinweis:</strong> ${esc(q.hint)}</div>`}}else document.querySelector('#next').onclick=()=>{S.i++;save();renderQ()};document.querySelector('#quit').onclick=homeView}
function answer(q,k){S.answers[q.id]={sel:k,ok:k===q.a,hint:!!q._hintUsed};delete q._hintUsed;save();renderQ()}
function stats(){const ans=Object.entries(S.answers).map(([id,a])=>({q:Q.find(x=>x.id===id),...a})).filter(x=>x.q),group={};for(const x of ans){const key=x.q.topic;group[key]||={n:0,c:0,h:0,part:x.q.part};group[key].n++;group[key].c+=x.ok?1:0;group[key].h+=x.hint?1:0}return{ans,group}}
function results(){home.classList.add('hidden');quiz.classList.add('hidden');result.classList.remove('hidden');const {ans,group}=stats(),correct=ans.filter(x=>x.ok).length,hints=ans.filter(x=>x.hint).length,pct=ans.length?Math.round(correct/ans.length*100):0,wrong=ans.filter(x=>!x.ok);const rows=Object.entries(group).sort((a,b)=>a[1].c/a[1].n-b[1].c/b[1].n).map(([t,g])=>{const p=Math.round(g.c/g.n*100);return `<tr><td>${esc(t)}<div class="small muted">${g.part}</div></td><td>${g.c}/${g.n}</td><td><div class=bar><span style="width:${p}%"></span></div>${p}%</td><td>${g.h}</td></tr>`}).join('');result.innerHTML=`<h2>Diagnose</h2><div class=grid><div class=stat><strong>${correct}/${ans.length}</strong>richtig</div><div class=stat><strong>${pct}%</strong>Trefferquote</div><div class=stat><strong>${hints}</strong>Hinweise</div><div class=stat><strong>${wrong.length}</strong>Fehler</div></div><p class="small muted">Die Prozentwerte sind eine Lernstandsdiagnose, keine offizielle TUM-Notenskala. Besonders aussagekräftig sind Themen mit mehreren beantworteten Fragen und ohne Hinweis.</p><table class=result-table><thead><tr><th>Thema</th><th>Richtig</th><th>Quote</th><th>Hinweise</th></tr></thead><tbody>${rows}</tbody></table><div class=actions><button class=primary id=resume>${S.i<S.order.length?'Test fortsetzen':'Zur Übersicht'}</button>${wrong.length?'<button class=secondary id=retry>Nur Fehler wiederholen</button>':''}<button class=secondary id=copy>Ergebnisbericht kopieren</button></div><h3>Bericht für ChatGPT</h3><textarea class=report id=report readonly>${esc(reportText(ans,group))}</textarea>`;document.querySelector('#resume').onclick=()=>S.i<S.order.length?renderQ():homeView;if(wrong.length)document.querySelector('#retry').onclick=()=>{S={order:shuffle(wrong.map(x=>x.q.id)),i:0,answers:{},mode:'wrong'};save();renderQ()};document.querySelector('#copy').onclick=async()=>{await navigator.clipboard.writeText(document.querySelector('#report').value);document.querySelector('#copy').textContent='Kopiert ✓'}}
function reportText(ans,group){const correct=ans.filter(x=>x.ok).length;let s=`AMOC DIAGNOSE – ERGEBNISBLATT\nGesamt: ${correct}/${ans.length} richtig (${ans.length?Math.round(correct/ans.length*100):0}%) | Hinweise: ${ans.filter(x=>x.hint).length}\n\nTHEMEN:\n`;for(const [t,g] of Object.entries(group).sort((a,b)=>a[1].c/a[1].n-b[1].c/b[1].n))s+=`- ${g.part} / ${t}: ${g.c}/${g.n} richtig, Hinweise ${g.h}\n`;s+='\nFALSCHE ANTWORTEN:\n';for(const x of ans.filter(x=>!x.ok))s+=`\n[${x.q.part} | ${x.q.topic}] ${x.q.q}\nMeine Antwort: ${x.q.opts[x.sel].t}\nRichtig: ${x.q.opts[x.q.a].t}\nHinweis benutzt: ${x.hint?'ja':'nein'}\n`;s+='\nBitte analysiere meine falschen Antworten, erkläre das Denkproblem und gib mir danach gezielte Wiederholungsfragen.';return s}
document.querySelector('#reset').onclick=()=>{if(confirm('Gesamten gespeicherten AMOC-Fortschritt löschen?')){localStorage.removeItem(LS);S={order:[],i:0,answers:{},mode:'full'};homeView()}};homeView();