const A=[];let n=1;function add(part,topic,q,opts,a,hint){A.push({id:n++,part,topic,q,opts:opts.map(x=>({t:x[0],e:x[1]})),a,hint})}
// TEIL 1 — Grundlagen, Moleküle, Symmetrie, Bindung, Komplexchemie
add('Teil 1','Atombau','Welche Aussage beschreibt |ψ|² im quantenmechanischen Atommodell am treffendsten?',[
['Es ist proportional zur Aufenthaltswahrscheinlichkeitsdichte des Elektrons.','Richtig: |ψ|² liefert die Wahrscheinlichkeitsdichte.'],['Es ist die Energie des Elektrons.','Die Energie folgt aus dem Hamiltonoperator und Eigenwert, nicht direkt aus |ψ|².'],['Es ist die Ladungsdichte des Atomkerns.','ψ beschreibt hier den elektronischen Zustand, nicht den Kern.'],['Es ist die klassische Bahnkurve des Elektrons.','Das Orbitalmodell ersetzt gerade die klassische Bahnvorstellung.']],0,'Denke an die Bornsche Interpretation der Wellenfunktion.');
add('Teil 1','Atombau','Welche Kombination von Quantenzahlen ist für ein einzelnes Elektron nicht zulässig?',[
['n=2, l=2, m=0','Für n=2 darf l nur 0 oder 1 sein.'],['n=3, l=2, m=-2','Diese Kombination ist zulässig.'],['n=2, l=1, m=1','Diese Kombination ist zulässig.'],['n=1, l=0, m=0','Diese Kombination ist zulässig.']],0,'Für l gilt 0 ≤ l ≤ n−1.');
add('Teil 1','Atombau','Warum nimmt die effektive Kernladung innerhalb einer Periode im Allgemeinen zu?',[
['Die Kernladung steigt, während die zusätzliche Abschirmung durch Elektronen derselben Schale dies nicht vollständig kompensiert.','Das ist der zentrale Trend.'],['Die Zahl innerer Schalen nimmt bei jedem Element um eins zu.','Innerhalb einer Periode bleibt die Zahl besetzter Hauptschalen typischerweise gleich.'],['Die Kernladung bleibt konstant, aber die Elektronenmasse steigt.','Die Protonenzahl steigt tatsächlich.'],['Die Valenzelektronen schirmen den Kern stärker ab als innere Elektronen.','Valenzelektronen schirmen sich gegenseitig vergleichsweise unvollständig ab.']],0,'Vergleiche Zunahme von Z mit der Abschirmung in derselben Hauptschale.');
add('Teil 1','Atombau','Was besagt die Hundsche Regel für entartete Orbitale?',[
['Sie werden zunächst einzeln mit parallelem Spin besetzt.','Richtig: maximale Zahl ungepaarter Elektronen vor Paarung.'],['Sie werden sofort paarweise mit entgegengesetztem Spin besetzt.','Das widerspricht der Hundschen Regel.'],['Nur ein Orbital eines entarteten Satzes darf besetzt werden.','Alle entarteten Orbitale können besetzt werden.'],['Die Spinrichtung ist durch die Hauptquantenzahl festgelegt.','Die Hauptquantenzahl legt den Spin nicht fest.']],0,'Denke an p³ oder d⁵ im freien Atom.');
add('Teil 1','Moleküle & VSEPR','Welche Geometrie erwartet das VSEPR-Modell für AX4E?',[
['Wippe / seesaw','Aus trigonal-bipyramidaler Elektronenpaargeometrie mit einem freien Elektronenpaar entsteht die Wippenform.'],['Tetraedrisch','AX4 ohne freies Elektronenpaar wäre tetraedrisch.'],['Quadratisch planar','Das ist typisch für AX4E2.'],['T-förmig','Das ist typisch für AX3E2.']],0,'Zähle zuerst alle Elektronendomänen.');
add('Teil 1','Moleküle & VSEPR','Warum besetzen freie Elektronenpaare in einer trigonal-bipyramidalen Elektronenpaargeometrie bevorzugt äquatoriale Positionen?',[
['Dort treten weniger 90°-Wechselwirkungen auf.','Äquatorial hat ein freies Elektronenpaar weniger ungünstige 90°-Kontakte.'],['Dort sind die Bindungen grundsätzlich kürzer.','Bindungslänge ist nicht die primäre VSEPR-Begründung.'],['Weil freie Elektronenpaare nur in der Molekülebene existieren können.','Das ist falsch.'],['Weil axiale Positionen keine p-Orbitale enthalten.','VSEPR argumentiert nicht so.']],0,'Vergleiche die Zahl der 90°-Nachbarn axial und äquatorial.');
add('Teil 1','Moleküle & VSEPR','Welche Aussage erklärt, warum NH3 stärker pyramidalisiert ist als PH3 im einfachen Bindungsbild?',[
['Bei NH3 ist sp³-Hybridisierung ein brauchbareres Modell; bei PH3 sind die P–H-Bindungen stärker p-orbitalartig.','Das beschreibt den in der Vorlesung diskutierten Trend zu weniger Hybridisierung bei schwereren Hauptgruppenelementen.'],['PH3 besitzt keine freien Elektronenpaare.','PH3 besitzt ein freies Elektronenpaar.'],['NH3 ist trigonal planar.','NH3 ist trigonal pyramidal.'],['Phosphor kann grundsätzlich keine p-Orbitale zur Bindung benutzen.','Das Gegenteil ist der Fall.']],0,'Denke an die abnehmende Bedeutung von Hybridisierung bei schwereren Elementen.');
add('Teil 1','Moleküle & VSEPR','Welche Aussage zu Resonanzstrukturen ist korrekt?',[
['Die reale Struktur ist nicht ein schnelles Umschalten, sondern wird als Resonanzhybrid beschrieben.','Resonanzformeln sind Grenzstrukturen einer delokalisierten Elektronenverteilung.'],['Eine Resonanzstruktur ist immer messbar isolierbar.','Grenzstrukturen sind im Allgemeinen keine separat isolierbaren Spezies.'],['Resonanz verändert die Atompositionen, nicht die Elektronenverteilung.','Bei Resonanz bleibt das Atomgerüst gleich; die Elektronenverteilung ändert sich.'],['Nur Moleküle mit formaler Gesamtladung können Resonanz zeigen.','Auch neutrale Moleküle können Resonanz zeigen.']],0,'Das Atomgerüst bleibt gleich.');
add('Teil 1','Symmetrie','Welche Symmetrieoperation gehört zu einer C3-Achse?',[
['Rotation um 120°','360°/3 = 120°.'],['Rotation um 90°','Das entspräche C4.'],['Spiegelung an einer Ebene','Das wäre σ, keine Cn-Operation.'],['Inversion durch ein Zentrum','Das wäre i.']],0,'Allgemein beträgt der Rotationswinkel 360°/n.');
add('Teil 1','Symmetrie','Welche Punktgruppe hat trigonal-bipyramidales PF5?',[
['D3h','PF5 besitzt C3, drei C2-Achsen senkrecht dazu und eine horizontale Spiegelebene.'],['C3v','Das wäre z.B. passend für NH3.'],['D4h','Das passt zu quadratisch-planarem XeF4.'],['Td','Das passt zu ideal tetraedrischen Molekülen.']],0,'Achte auf die horizontale Spiegelebene durch die drei äquatorialen F-Atome.');
add('Teil 1','Symmetrie','Welche Punktgruppe besitzt quadratisch-planare XeF4-Geometrie?',[
['D4h','Quadratisch-planar mit C4-Achse, C2-Achsen, Spiegelung und Inversionszentrum.'],['Td','Tetraedrisch wäre eine andere Geometrie.'],['C4v','Das Inversionszentrum und die horizontale Spiegelebene würden fehlen.'],['D2h','Die C4-Achse macht D2h zu niedrigsymmetrisch.']],0,'Die höchste Drehachse ist C4 und das Molekül ist planar.');
add('Teil 1','Symmetrie','Warum kann BF3 eine andere Punktgruppe besitzen als BF2H, obwohl beide trigonal-planar sein können?',[
['Unterschiedliche Substituenten können Symmetrieoperationen zerstören, obwohl die Grundgeometrie ähnlich bleibt.','Punktgruppen hängen von der tatsächlichen Identität und Anordnung der Atome ab.'],['Punktgruppen hängen ausschließlich vom Zentralatom ab.','Die gesamte Molekülstruktur ist relevant.'],['BF2H ist nicht planar möglich.','Planarität allein entscheidet die Punktgruppe nicht.'],['Symmetrieoperationen ignorieren die Identität der Atome.','Sie müssen das Molekül auf eine ununterscheidbare Konfiguration abbilden.']],0,'Eine Symmetrieoperation muss gleiche Atomsorten aufeinander abbilden.');
add('Teil 1','Kovalente Bindung & MO','Warum ist O2 im MO-Modell paramagnetisch?',[
['Es besitzt zwei ungepaarte Elektronen in π*-Orbitalen.','Das ist die charakteristische MO-Erklärung.'],['Es besitzt eine O–O-Einfachbindung.','Die Bindungsordnung ist im MO-Modell 2.'],['Alle bindenden Orbitale sind einfach besetzt.','Die ungepaarten Elektronen sitzen in antibindenden π*-Orbitalen.'],['Ein Sauerstoffatom trägt formal O+ und das andere O−.','Das erklärt den Paramagnetismus nicht.']],0,'Betrachte die Besetzung der höchsten besetzten π*-Orbitale.');
add('Teil 1','Kovalente Bindung & MO','Bei einem heteronuklearen zweiatomigen Molekül liegt ein bindendes MO energetisch typischerweise näher an welchem AO?',[
['Am energieärmeren AO des elektronegativeren Atoms.','Das bindende MO hat größeren Anteil am tieferliegenden AO.'],['Immer exakt in der Mitte beider AO-Energien.','Bei heteronuklearen Molekülen sind die AO-Energien verschieden.'],['Am energiereicheren AO des elektropositiveren Atoms.','Das antibindende MO hat relativ mehr Charakter des energiereicheren AO.'],['Die Elektronegativität spielt im MO-Bild keine Rolle.','Sie beeinflusst die AO-Energien und damit die MO-Zusammensetzung.']],0,'Das energieärmere AO trägt stärker zum bindenden MO bei.');
add('Teil 1','Kovalente Bindung & MO','Welche Beschreibung ist für XeF2 bzw. I3− als hypervalente lineare Spezies besonders geeignet?',[
['Eine 3-Zentren-4-Elektronen-Bindung.','Das Mehrzentren-MO-Modell beschreibt diese Spezies ohne d-Orbital-Expansion.'],['Zwei unabhängige klassische Doppelbindungen.','Das passt weder zur Elektronenzahl noch zum Bindungsbild.'],['Eine 3-Zentren-2-Elektronen-Bindung.','Das ist typisch für elektronenarme Brücken wie B–H–B, nicht für XeF2/I3−.'],['Zwingende sp3d-Hybridisierung mit stark beteiligten d-Orbitalen.','Die Vorlesung bevorzugt das Mehrzentren-MO-Bild statt d-Orbital-Expansion.']],0,'Hypervalenz und Elektronenmangel sind nicht dasselbe.');
add('Teil 1','Kovalente Bindung & MO','Welche Aussage zur d-Orbital-Beteiligung bei Hypervalenz trifft die moderne MO-Beschreibung am besten?',[
['Hypervalente Bindung lässt sich ohne wesentliche d-Orbital-Expansion durch Mehrzentren-MOs erklären.','Das ist die zentrale moderne Beschreibung.'],['Hypervalenz ist nur möglich, wenn d-Orbitale vollständig besetzt sind.','Das ist nicht die Ursache von Hypervalenz.'],['Jede hypervalente Bindung ist eine Metall-Metall-Bindung.','Hypervalenz betrifft auch Hauptgruppenmoleküle.'],['d-Orbitale des Liganden übernehmen immer alle Elektronen.','Das ist keine allgemeine Beschreibung.']],0,'Denke an XeF2/I3− und 3c4e.');
add('Teil 1','Komplexchemie Grundlagen','Was bedeutet „homoleptisch“ bei einem Komplex?',[
['Es ist nur eine Ligandenart vorhanden.','Homoleptisch bezieht sich auf die Identität der Liganden.'],['Alle Liganden sind einzähnig.','Denticität ist davon unabhängig; en kann z.B. bidentat sein.'],['Der Komplex ist ungeladen.','Die Gesamtladung ist irrelevant für homoleptisch/heteroleptisch.'],['Das Metall besitzt Oxidationsstufe 0.','Auch das ist unabhängig davon.']],0,'Frage dich, ob alle Liganden chemisch gleich sind.');
add('Teil 1','Komplexchemie Grundlagen','Welche Aussage beschreibt die Koordinationszahl am besten?',[
['Sie zählt die direkt an das Zentralatom gebundenen Donoratome.','Das ist die gebräuchliche Definition.'],['Sie ist immer identisch mit der Zahl der Ligandenmoleküle.','Mehrzähnige Liganden machen diese Zahlen verschieden.'],['Sie ist die Oxidationszahl des Metalls.','Das sind verschiedene Größen.'],['Sie entspricht der Zahl ungepaarter d-Elektronen.','Auch das ist unabhängig.']],0,'Bei einem bidentaten Liganden trägt ein Ligand zwei Donoratome bei.');
add('Teil 1','Komplexchemie Grundlagen','Welche KZ=5-Geometrien sind besonders wichtig?',[
['Trigonal-bipyramidal und quadratisch-pyramidal','Beide sind typische Fünfkoordinationen.'],['Tetraedrisch und quadratisch-planar','Beide sind KZ=4.'],['Oktaedrisch und trigonal-prismatisch','Beide sind KZ=6.'],['Linear und gewinkelt','Beide betreffen KZ=2.']],0,'Fünf Liganden lassen sich in zwei grundlegenden Geometrien anordnen.');