window.AMOC_TYPE2=[];
let T2ID=1;
function t2(part,topic,q,c,w1,w2,w3,hint){
  window.AMOC_TYPE2.push({id:T2ID++,part,topic,q,opts:[
    {t:c,e:"Richtig – genau so ist es in den AMOC-Folien dargestellt."},
    {t:w1,e:"Das passt nicht zur Darstellung in den AMOC-Folien."},
    {t:w2,e:"Diese Zuordnung entspricht nicht den Folien."},
    {t:w3,e:"Das ist nicht die in den Folien behandelte Aussage."}
  ],a:0,hint});
}
// MO/LGO/Mehrzentrenbindung
t2("Teil 1","MO & LGO","Welche Symmetrie besitzen die drei Ligandengruppenorbitale des H3-Gerüsts in trigonal-planarem BH3?","a1′ + e′","a1g + t1u","a2″ + e″","a1 + b1 + b2","BH3 besitzt D3h-Symmetrie.");
t2("Teil 1","MO & LGO","Welche Aussage zum H3-Fragment in BH3 entspricht der Folie?","Die drei H-1s-Orbitale kombinieren zu einem nicht entarteten a1′-LGO und einem zweifach entarteten e′-Satz.","Alle drei H-1s-Orbitale bleiben energetisch und symmetriebezogen unabhängig.","Es entsteht nur ein dreifach entartetes t2-LGO.","Das H3-Fragment liefert ausschließlich π-LGOs.","Ein symmetrisches und ein zweifach entartetes LGO-Paket.");
t2("Teil 1","MO & LGO","Welche Punktgruppe wird für das MO-Diagramm von trigonal-planarem BH3 verwendet?","D3h","C3v","Td","D∞h","Planar + C3 + horizontale Spiegelebene.");
t2("Teil 1","MO & LGO","Welche Punktgruppe wird für das MO-Diagramm von trigonal-pyramidalem NH3 verwendet?","C3v","D3h","Td","C2v","NH3 ist pyramidal, nicht planar.");
t2("Teil 1","MO & LGO","Welche Kombination beschreibt die Ligandengruppenorbitale von tetraedrischem CH4 qualitativ?","Ein totalsymmetrisches LGO und ein dreifach entarteter Satz.","Zwei zweifach entartete Sätze ohne totalsymmetrische Kombination.","Vier vollständig unabhängige nicht entartete LGOs.","Nur ein einziges LGO.","Vier H-1s-Orbitale in Td.");
t2("Teil 1","MO & LGO","Welche zusätzliche Wechselwirkung unterscheidet das MO-Bild von BF3 gegenüber BH3 besonders?","Fluor-2p-Orbitale können π-Wechselwirkungen mit Bor eingehen.","Fluor besitzt keine p-Orbitale und kann nur ionisch binden.","Bor verwendet zwingend d-Orbitale für die π-Bindung.","BF3 besitzt keine σ-Bindungen.","Vergleiche BF3 ausdrücklich mit BH3.");
t2("Teil 1","MO & LGO","Welche Aussage zum MO-Modell von BF3 ist auf der Vergleichsfolie angegeben?","Neben drei bindenden σ-MOs gibt es bindende π-MOs und ein antibindendes π-MO.","BF3 besitzt ausschließlich drei lokalisierte σ-MOs und keinerlei π-Anteil.","Alle π-MOs von BF3 sind besetzt antibindend.","Die B–F-Bindungen sind im MO-Modell rein ionisch.","Die Folie vergleicht VB- und MO-Bild.");
t2("Teil 1","MO & LGO","Welche radialen LGOs des F6-Fragments werden für oktaedrisches SF6 angegeben?","a1g, t1u und eg","a1′, e′ und a2″","t2g und t2u","b1g, b2g und eu","Oh-Symmetrie; radiale LGOs koppeln an passende S-AOs.");
t2("Teil 1","MO & LGO","Welche Aussage trifft im einfachen σ-only-MO-Schema eines oktaedrischen Komplexes zu?","t2g ist M–L-nichtbindend, eg* ist M–L-antibindend.","t2g ist stark M–L-antibindend und eg* nichtbindend.","Alle fünf d-Orbitale bleiben nichtbindend.","eg ist grundsätzlich π-bindend.","Reiner 2e-σ-Donor-Ligand.");
t2("Teil 1","MO & LGO","Was bewirkt ein π-Donor-Ligand im oktaedrischen MO-Schema?","Die ursprünglich nichtbindenden t2g-Orbitale werden angehoben und Δokt wird kleiner.","t2g wird stark stabilisiert und Δokt wird größer.","eg* wird zu einem bindenden Orbital.","Die d-Orbitale bleiben vollständig unbeeinflusst.","π-Donation koppelt an die t2g-Symmetrie.");
t2("Teil 1","MO & LGO","Was bewirkt ein π-Akzeptor-Ligand wie CO im oktaedrischen MO-Schema?","Die t2g-artigen Metallorbitale werden stabilisiert und Δokt wird größer.","Δokt wird kleiner, weil t2g angehoben wird.","eg* wird vollständig nichtbindend.","CO wirkt ausschließlich als π-Donor.","Rückbindung in leere π*-Orbitale.");
t2("Teil 1","Mehrzentrenbindung","Welche Zuordnung ist korrekt?","BeH2/B2H6: 3-Zentren-2-Elektronen; XeF2/I3−: 3-Zentren-4-Elektronen.","BeH2/B2H6: 3c4e; XeF2/I3−: 3c2e.","Alle vier Spezies werden ausschließlich durch 2c2e-Bindungen beschrieben.","Nur XeF2 besitzt eine Mehrzentrenbindung.","Elektronenmangel vs. Hypervalenz auseinanderhalten.");
t2("Teil 1","Mehrzentrenbindung","Was unterscheidet 3c2e- und 3c4e-Bindungen konzeptionell?","3c2e stabilisiert elektronenarme Systeme; 3c4e beschreibt hypervalente lineare Bindungseinheiten.","3c2e ist immer ionisch, 3c4e immer metallisch.","3c2e kommt nur bei Übergangsmetallen vor, 3c4e nur bei Bor.","Beide Begriffe sind vollständig synonym.","Diboran versus XeF2.");
t2("Teil 1","Mehrzentrenbindung","Wie werden die axialen P–F-Bindungen in PF5 auf der Folie beschrieben?","Als 3-Zentren-4-Elektronen-Bindungseinheit.","Als 3-Zentren-2-Elektronen-Bindung wie in Diboran.","Als klassische P=F-Doppelbindungen.","Als rein ionische P+F−-Paare ohne Mehrzentrenanteil.","Axial ≠ äquatorial.");

// Gruppe 1/2
t2("Teil 2","Gruppen 1 & 2","Welche Clusterklassifikation reproduziert die Folie exakt?","3 ≤ n ≤ 12 Mikrocluster; 12 ≤ n ≤ 100 kleine Cluster; n > 100 große Cluster/Nanokristalle.","2 ≤ n ≤ 6 Mikrocluster; 7 ≤ n ≤ 20 kleine Cluster; n > 20 Nanokristalle.","3 ≤ n ≤ 100 Mikrocluster; n > 100 ausschließlich Bulkmetall.","n < 12 Nanokristalle; n > 100 Mikrocluster.","Die Folie setzt die Grenzen bei 12 und 100.");
t2("Teil 2","Gruppen 1 & 2","Wie charakterisiert die Folie Metallcluster allgemein?","Definierte mehrkernige Metallkomplexe mit M–M-Bindungen, zwischen Molekül und Metall.","Reine Ionengitter ohne Metall–Metall-Kontakte.","Ausschließlich gasförmige zweiatomige Moleküle.","Nur organische Makromoleküle mit Metallionen.","„Zwischen Molekül und Metall“.");
t2("Teil 2","Gruppen 1 & 2","Welche Wirkung hat THF typischerweise auf Organolithium-Aggregate?","Als Donor-Lösungsmittel verringert THF den Aggregationsgrad.","THF erhöht den Aggregationsgrad zwingend bis zum Polymer.","THF protoniert Organolithiumverbindungen quantitativ.","THF oxidiert Li(I) zu Li(II).","Donorliganden koordinieren Li+ und brechen Aggregate auf.");
t2("Teil 2","Gruppen 1 & 2","Welche Kombination wird auf der Organolithium-Strukturfolie gezeigt?","(MeLi)4 sowie n-BuLi als Tetramer in Ether und Hexamer in Kohlenwasserstoff.","MeLi ausschließlich monomer und n-BuLi ausschließlich dimer.","MeLi als Hexamer und n-BuLi unabhängig vom Lösungsmittel immer monomer.","Alle Organolithiumverbindungen sind Ionengitter ohne Aggregate.","Lösungsmittel beeinflusst den Aggregationsgrad.");
t2("Teil 2","Gruppen 1 & 2","Wie verändert zunehmende sterische Hinderung bei Organolithiumreagenzien laut Folie Nukleophilie und Basizität?","Die Nukleophilie nimmt ab, die Basizität bleibt weitgehend erhalten.","Beide nehmen stark ab.","Die Nukleophilie steigt, die Basizität sinkt.","Nur die Basizität verschwindet.","Sperrig = schlechterer C-Angriff, aber starke Base.");
t2("Teil 2","Gruppen 1 & 2","Welche Reaktion beschreibt die CO2-Fixierung mit einem Organolithiumreagenz?","RLi + CO2 → RCO2Li","RLi + CO2 → RH + Li2CO3","RLi + CO2 → R2CO + Li2O","RLi + CO2 → LiH + CO","Carboxylierung des organischen Restes.");
t2("Teil 2","Gruppen 1 & 2","Wofür dient NaCp laut Folie besonders?","Als wichtige Vorstufe zur Synthese von Metallocenen wie Ferrocen.","Als Oxidationsmittel im Ostwald-Verfahren.","Als Ligand für Xenonfluoride.","Als Trockenmittel für Phosphorsäure.","Cp = Cyclopentadienyl.");
t2("Teil 2","Gruppen 1 & 2","Welche Bindungsstärkereihenfolge ist für [M(18-crown-6)]+ angegeben?","K+ > Rb+ > Cs+ ≈ Na+ > Li+","Li+ > Na+ > K+ > Rb+ > Cs+","Cs+ > Rb+ > K+ > Na+ > Li+","Na+ > Li+ > K+ > Cs+ > Rb+","18-crown-6 passt besonders gut zu K+.");
t2("Teil 2","Gruppen 1 & 2","Welche Bindungsstärkereihenfolge ist für [M([2.2.2]crypt)]2+ angegeben?","Ba2+ > Sr2+ >> Ca2+ > Mg2+","Mg2+ > Ca2+ >> Sr2+ > Ba2+","Ca2+ > Mg2+ > Ba2+ > Sr2+","Sr2+ > Mg2+ > Ca2+ > Ba2+","Großer Kryptand begünstigt die größeren Erdalkalikationen.");
t2("Teil 2","Gruppen 1 & 2","Warum binden Kryptanden Kationen meist stärker als Kronenether?","Sie umschließen das Kation dreidimensional und wirken wie eine künstliche Solvathülle.","Sie oxidieren das Kation zu einer höheren Oxidationsstufe.","Sie besitzen keine Donoratome.","Sie bilden zwingend Metall–Metall-Bindungen.","Dreidimensionale Einkapselung.");
t2("Teil 2","Gruppen 1 & 2","Welche Aussage zur Hydratation kleiner Kationen ist folienkonform?","Kleine Ionen mit hoher Ladungsdichte wie Li+ und Be2+ besitzen große Hydratations-/Solvatisierungsenergien.","Große Cs+-Ionen besitzen stets die größte Hydratationsenergie.","Hydratation ist unabhängig von Ladungsdichte und Radius.","Nur Anionen können hydratisiert werden.","Hohe Ladungsdichte = starke Wechselwirkung mit Wasser.");
t2("Teil 2","Gruppen 1 & 2","Welche Aussage zu BeH2 trifft die Folie?","Es ist ein kovalentes elektronenarmes Kettensystem mit Brücken-H und 3c2e-Bindungen.","Es besteht im Festkörper aus isolierten linearen Molekülen.","Es ist ein typisches ionisches Hydrid.","Es enthält ausschließlich Be=H-Doppelbindungen.","Vergleich mit Diboran.");
t2("Teil 2","Gruppen 1 & 2","Welche Aussage zu BeCl2 ist korrekt?","Im Feststoff polar-kovalentes Koordinationspolymer, in der Gasphase linear.","Im Feststoff lineare Monomere, in der Gasphase Ionengitter.","In allen Phasen tetraedrisches BeCl4.","BeCl2 ist ein typisches NaCl-artiges Ionengitter.","Feststoff ≠ Gasphase.");

// Gruppe 13
t2("Teil 2","Gruppe 13","Wie ist Borsäure in den Folien charakterisiert?","Als Lewis-Säure, nicht als klassische Brønsted-Säure.","Als starke dreiprotonige Brønsted-Säure analog H3PO4.","Als Lewis-Base ohne Säurefunktion.","Als ausschließlich redoxaktive Verbindung.","Acidität über Lewis-Säureverhalten.");
t2("Teil 2","Gruppe 13","Welches Strukturmotiv entsteht bei der Kondensation von Borsäure?","B–O–B-Brücken.","B–B-Dreifachbindungen.","Nur B–H–B-Brücken.","Metallische B–B-Netzwerke.","Entwässerung/Kondensation.");
t2("Teil 2","Gruppe 13","Welche Rolle spielt Pinakol in der Organoborchemie laut Folie?","Es bildet Boronsäureester als wichtige Schutz- und Funktionsgruppe.","Es reduziert Borsäure zu elementarem Bor.","Es spaltet B–O-Bindungen hydrolytisch.","Es bildet ausschließlich Borhydride.","Vicinales Diol + Bor.");
t2("Teil 2","Gruppe 13","Was ist die zentrale Anwendung der Boronsäure-/Boronsäureesterchemie auf der Folie?","Suzuki-Kupplung zur Pd-katalysierten C–C-Bindungsbildung.","Ziegler-Natta-Polymerisation.","Ostwald-Oxidation.","Kontaktverfahren.","Akira Suzuki.");
t2("Teil 2","Gruppe 13","Warum ist Borazin deutlich reaktiver als Benzol?","Unvollständige Elektronendelokalisierung und polare B–N-Bindungen führen zu geringerer Aromatizität.","Borazin besitzt stärkere vollständige π-Delokalisierung als Benzol.","Borazin enthält keine π-Elektronen.","Borazin ist ein Ionengitter.","„Anorganisches Benzol“, aber nicht gleich aromatisch.");
t2("Teil 2","Gruppe 13","Wo greift ein Nukleophil am Borazin bevorzugt an?","Am Bor-Zentrum.","Am Stickstoff-Zentrum.","Nur am Wasserstoff.","Nukleophile können Borazin nicht angreifen.","B ist der elektropositivere Ringpartner.");
t2("Teil 2","Gruppe 13","Welche Aussage zu AlH3 und B2H6 ist richtig?","B2H6 ist diskret molekular; AlH3 ist ein polymerer Feststoff mit Al–H–Al-Brücken.","AlH3 ist diskret molekular und B2H6 ein Ionengitter.","Beide liegen ausschließlich als Monomere vor.","Beide sind klassische ionische Hydride.","AlH3 polymerisiert stärker.");
t2("Teil 2","Gruppe 13","Was bewirken Donorliganden wie THF bei AlH3?","Sie brechen die polymere Struktur auf und stabilisieren monomere Addukte.","Sie oxidieren AlH3 zu AlCl3.","Sie erzeugen Al–Al-Doppelbindungen.","Sie entfernen Hydrid als H+.","Lewis-Base stabilisiert elektronenarmes AlH3.");
t2("Teil 2","Gruppe 13","Warum ist LiAlH4 stärker reduzierend als NaBH4?","Al ist größer/elektropositiver; Al–H ist länger und stärker polarisiert, sodass Hydrid leichter übertragen wird.","B–H ist stärker hydridisch als Al–H.","Na+ macht BH4− grundsätzlich reaktiver.","LiAlH4 enthält keine hydridischen H-Atome.","Vergleiche Al–H und B–H.");
t2("Teil 2","Gruppe 13","Welche Phase-/Aggregationsfolge von AlCl3 wird auf der Folie gezeigt?","Festkörpergitter → Al2Cl6-Dimer in Flüssigkeit/Gas → AlCl3-Monomer bei hoher Temperatur.","Monomer im Feststoff → Polymer im Gas → Ionengitter bei hoher Temperatur.","AlCl3 bleibt in allen Phasen monomer.","AlCl3 liegt immer als [AlCl4]− vor.","Elektronenmangel fördert Dimerisierung.");
t2("Teil 2","Gruppe 13","Wie verändert sich die Stabilität der Gruppe-13-Hydride B → Al → Ga?","Sie nimmt ab.","Sie nimmt stark zu.","Sie bleibt konstant.","Kein systematischer Trend.","Schwächere E–H-Bindungen nach unten.");
t2("Teil 2","Gruppe 13","Was bedeutet der Inert-Pair-Effekt für die schweren Triele?","Die Oxidationsstufe +1 wird nach unten stabiler, +3 weniger stabil.","+3 wird nach unten immer stabiler und +1 verschwindet.","Nur Oxidationsstufe 0 bleibt möglich.","Der Effekt betrifft ausschließlich Bindungswinkel.","ns2-Elektronen werden schlechter für Bindungen verfügbar.");
t2("Teil 2","Gruppe 13","Welche Aussage zu Al(I)-Verbindungen entspricht der Folie?","[Cp*Al]4 ist ein Al(I)-Cluster; sehr sperrige Terphenyl-Liganden können monovalentes Al(I) stabilisieren.","Al(I) ist grundsätzlich unmöglich.","Al(I) existiert nur als freies Al+ in der Gasphase.","Kleine Liganden stabilisieren monomeres Al(I) am besten.","Sterische Abschirmung verhindert Aggregation.");
