// Fragentyp 2 – Gruppe 14
t2("Teil 2","Gruppe 14","Warum lassen sich Silylether besonders selektiv mit Fluorid entschützen?","Die sehr starke Si–F-Bindung treibt die Spaltung an.","Fluorid protoniert den Alkohol besonders stark.","F− oxidiert Si(IV) zu Si(VI).","Fluorid greift ausschließlich am Sauerstoff an und bildet O–F.","TBAF und starke Si–F-Bindung.");
t2("Teil 2","Gruppe 14","Welche Rolle spielt Hyperkoordination bei Reaktionen von Silylethern?","Hyperkoordinierte Si-Zwischenstufen erleichtern Substitutionen am Silicium.","Hyperkoordination verhindert jeden nukleophilen Angriff.","Sie reduziert Silicium zu elementarem Si.","Sie kommt bei Silicium nicht vor.","Silicium kann seine Koordinationszahl vorübergehend erhöhen.");
t2("Teil 2","Gruppe 14","Welche Orbitalwechselwirkung beschreibt den α-Silyleffekt?","n(C−) → σ*(Si–C).","σ(Si–C) → p(C+).","π(C=C) → π*(Si=Si).","σ*(Si–C) → n(C−).","α stabilisiert Carbanionen.");
t2("Teil 2","Gruppe 14","Welche Orbitalwechselwirkung beschreibt den β-Silyleffekt?","σ(C–Si) → p(C+).","n(C−) → σ*(Si–C).","p(C+) → σ(C–Si).","σ*(C–C) → d(Si).","β stabilisiert Carbokationen.");
t2("Teil 2","Gruppe 14","Warum ist Hyperkonjugation mit Si stärker als beim Kohlenstoffanalogon?","Die 3p-Orbitale von Si sind größer und energetisch besser angepasst.","Silicium besitzt keine p-Orbitale.","Nur Kohlenstoff kann Hyperkonjugation zeigen.","Die Si–C-Bindung ist rein ionisch.","Größe, Energiedifferenz und Überlappung.");
t2("Teil 2","Gruppe 14","Warum ist SiH4 pyrophor, CH4 dagegen luftstabil?","Schwächere Si–H-Bindung plus Bildung sehr starker Si–O-Bindungen begünstigen spontane Oxidation.","SiH4 besitzt eine stärkere Si–H-Bindung als CH4.","CH4 enthält hydridische H− und reagiert deshalb nicht.","SiH4 ist ionisch, CH4 metallisch.","Bindungsstärke Edukt vs. Produkt.");
t2("Teil 2","Gruppe 14","Welcher Trend gilt für EH4 von C nach Pb?","E–H-Bindungen werden schwächer, Hydridcharakter und Reduktionskraft nehmen zu.","E–H-Bindungen werden stärker und Reduktionskraft nimmt ab.","Hydridcharakter verschwindet vollständig.","Alle Hydride bleiben gleich stabil.","Schwere Tetrele bilden zunehmend instabile Hydride.");
t2("Teil 2","Gruppe 14","Welche Reaktion ist der HCl-Prozess zu Trichlorsilan?","Si + 3 HCl → HSiCl3 + H2","SiO2 + HCl → SiCl4 + H2O","Si + H2 → SiH4","HSiCl3 + H2O → Si + HCl","Wichtiges Zwischenprodukt für Silan/Reinstsilicium.");
t2("Teil 2","Gruppe 14","Warum hydrolysiert SiCl4 heftig, während CCl4 praktisch inert ist?","Starke Si–O-Bindungen treiben die Hydrolyse, und Si kann hyperkoordiniert werden.","C–Cl ist grundsätzlich ionisch und daher unreaktiv.","SiCl4 besitzt keine vollständige Valenzschale.","CCl4 hydrolysiert in Wahrheit schneller.","Produktstabilisierung + Hyperkoordination.");
t2("Teil 2","Gruppe 14","Welche Aussage zu elektronenziehenden Substituenten an Si–H gilt auf der HSiCl3-Folie?","Sie verstärken die Si–H-Bindung.","Sie schwächen die Si–H-Bindung grundsätzlich bis zur Spaltung.","Sie haben keinen Einfluss.","Sie machen H formal positiv und eliminieren jede Hydridreaktivität vollständig.","Vergleich substituierter Silane.");
t2("Teil 2","Gruppe 14","Was ist das Grundprinzip des Siemens-Prozesses zur Herstellung von Reinstsilicium?","Rohsilicium wird in flüchtige Chlorsilane überführt, durch Destillation hochgereinigt und anschließend wieder als hochreines Si abgeschieden.","SiO2 wird einmal mit Wasser extrahiert und direkt zu Reinstsilicium.","Reinstsilicium entsteht durch Elektrolyse von Na2SiO3 in Wasser.","Der Prozess verwendet ausschließlich elementares Fluor.","Flüchtige Chlorsilane sind der Reinigungsschritt.");
t2("Teil 2","Gruppe 14","Welche Ausgangsreaktion liefert zunächst Rohsilicium für den Siemens-Prozess?","SiO2 + 2 C → Si + 2 CO","SiCl4 + 2 H2O → Si + 4 HCl","SiF4 + 4 Na → SiO2 + 4 NaF","SiH4 + O2 → Si + 2 H2O","Carbothermische Reduktion.");
t2("Teil 2","Gruppe 14","Warum können [SiF5]− und [SiF6]2− stabil sein?","Die außergewöhnlich starke Si–F-Bindung macht zusätzliche Fluoridkoordination energetisch günstig.","Si–F ist außergewöhnlich schwach.","Silicium kann niemals mehr als vier Liganden koordinieren.","F− wirkt hier ausschließlich als Oxidationsmittel.","Hypervalente Fluorokomplexe.");
t2("Teil 2","Gruppe 14","Welche Besonderheit zeigen Germaniumhalogenide gegenüber Silicium besonders?","Stabile Dihalogenide der Oxidationsstufe +II sind ausgeprägter.","Ge bildet keine Halogenide.","Ge kennt ausschließlich +IV und keine niedrigere Oxidationsstufe.","GeCl4 kann kein zusätzliches Chlorid koordinieren.","Inert-Pair-Trend beginnt deutlicher zu werden.");
t2("Teil 2","Gruppe 14","Welcher Trend gilt von Si/Ge zu Sn/Pb für Halogenidchemie?","Niedrigere Oxidationsstufen und höhere Koordinationszahlen werden mit zunehmender Atomgröße stabiler.","Nur +IV wird nach unten immer dominanter.","Koordinationszahlen nehmen zwingend ab.","Halogenide verschwinden vollständig.","Schwere Tetrele: Inert-Pair + größerer Radius.");
t2("Teil 2","Gruppe 14","Was erklärt das CGMT-Modell?","Warum schwere E=E-Systeme trans-bent statt klassisch planar sein können.","Warum alle C=C-Doppelbindungen linear werden.","Warum Silicium keine Mehrfachbindungen bilden kann.","Warum nur Metall-Metall-Bindungen trans-bent sind.","Carter–Goddard–Malrieu–Trinquier.");
t2("Teil 2","Gruppe 14","Welche Fragmentzuordnung nennt die CGMT-Folie?","Kleiner sp2→p-Energieabstand begünstigt Triplett-Charakter; großer Abstand Singulett-Charakter.","Kleiner Abstand führt zwingend zum Singulett, großer zum Triplett.","Beide Fälle führen immer zum selben Zustand.","Die Spinlage spielt im Modell keine Rolle.","Besetzung des p-Orbitals entscheidet.");
